version: '2'

# launch: docker-compose up --build -d

services:
  CertStreamMonitor:
    image: certstreammonitor
    container_name: certstreammonitor
    hostname: certstreammonitor
    build:
      context: ../
      dockerfile: docker/Dockerfile
    #volumes:
    
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
